spring.application.name=tropimotos-backend

spring.datasource.url=jdbc:postgresql://ep-wandering-sun-ata3m49d-pooler.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hyeTszHGx28K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}

jwt.secret=TropiMotosSecretKey2024SuperSeguraYLargeParaTokenJWTQueDebeSerMuyLarga
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.com.tropimotos=DEBUG